- name: Disable MySQL 8 version
  ansible.builtin.shell: dnf module disable mysql -y
  # To use shell command in Ansible Playbook

- name: Setup the MySQL5.7 repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start and Enable MySQL Service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Disable MySQL 8 version
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1s
