- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: golang
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: Systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd