- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: app nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: Systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_role_module.html

