- name: install maven
  ansible.builtin.dnf:
    name: maven 
    state: present

- name: Install dependencies 
  ansible.builtin.command: mvn clean package
  args: 
    chdir: /app # to change the directory and run the command

- name: rename jar file 
  ansible.builtin.command: mv target/{{component}}-{{shipping_version}}.jar {{component}}.jar
  args:
    chdir: /app

