- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the catalogue entries count
  ansible.builtin.command: mongo --host mongodb.mydevops.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.product.count()'
  register: products_count
  when: component == "catalogue"

- name: get the user entries count
  ansible.builtin.shell: mongo --host mongodb.mydevops.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: "load catalogue data"
  ansible.builtin.shell: mongo --host mongodb.mydevops.online < /app/schema/catalogue.js
  when: products_count.stdout == "0" and component == "catalogue"

- name: "load user data"
  ansible.builtin.shell: "mongo --host mongodb.mydevops.online < /app/schema/{{component}}.js"
  when: component == "user" and users_count.stdout == "0" #keep double quots
  #ignore_errors: true
 