- name: disable old nodejs and enable nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y 
  # to use the the shell commands in ansible playbook

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install dependencies 
  ansible.builtin.command: npm install
  args: 
    chdir: /app # to change the directory and run the command